# SPDX-FileCopyrightText: 2022 Gonzalo López <glopezvigliante@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Feature Request (中文)
description: 为启动器建议一个想法
# title: ""
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: 您的功能请求是否与问题有关？请描述。
      description: 对问题的清晰和简洁的描述。例如：当 [...] 时我总是感到沮丧
    validations:
      required: false

  - type: textarea
    attributes:
      label: 描述您想要的解决方案
      description: 对您想要发生什么的清晰和简洁的描述。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 描述您考虑过的替代方案
      description: 对您考虑过的任何替代解决方案或功能的清晰和简洁的描述。
    validations:
      required: false

  - type: textarea
    attributes:
      label: 其他背景
      description: 在此处添加有关功能请求的其他背景或截图。
    validations:
      required: false

